### ISSUE TITLE
Pattern found#17 - PHP: multiple encoded, most probably obfuscated code found #11

### ISSUE THREAD

**Issue by Yiannistaos** [compojoom/jedchecker#27]
My Joomla! version is the 3.5.0-rc.

From JED Checker (component), I've got this.

> Rule Jamss - JAMSS - Joomla! Anti-Malware Scan Script
> #001 
> example.php in line: 63
> Pattern found#17 - PHP: multiple encoded, most probably obfuscated code found

My code in line 63 is:
$test = `preg_replace("/(plg_|com_|mod_)/", "$replacement_string", $string);`
echo $test;

Why is the code obfuscated? Can you give me another code example to pass the test?

Thanks.

**Comment by JazParkyn** [comment]
Hi,

In the JAMSS rule, one of the checks is for the presence of preg_replace, so it makes sense that this line of your code got flagged up for this. See line 115 link below for more info. 

The JAMSS script can highlight a lot of false positives, but we leave these checks in place to help find code where such functions are being used maliciously. 

Your extension will not fail the JED Checker because of this - JAMSS issues get flagged as warnings not errors.

https://github.com/compojoom/jedchecker/blob/master/source/administrator/components/com_jedchecker/libraries/rules/jamss.php#L115
